#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2
id = "docmost"
name = "Docmost"
description.en = "Collaborative wiki and documentation"
description.fr = "Wiki collaboratif et documentation"

version = "0.90.1~ynh1"

maintainers = ["otm33GH", "eric_G"]

[upstream]
license = "GPL-3.0-only"
website = "https://docmost.com/"
admindoc = "https://docmost.com/docs/"
code = "https://github.com/docmost/docmost"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "2000M"
ram.build = "1500M"
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/orhtej2/docmost-build/releases/download/v0.90.1/docmost.tar.gz"
    sha256 = "7a2a51213dd964f6c4bb09d2a77e79dca30bc20db8293920d1e4efeb296aa9ed"
    
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/orhtej2/docmost-build"
    autoupdate.asset = "docmost.tar.gz"

    [resources.system_user]
	allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]

    [resources.apt]
    packages = "postgresql, redis-server"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"
